// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sigcorp.Models;

namespace Sigcorp.Migrations
{
    [DbContext(typeof(SigcorpContext))]
    [Migration("20190719025620_OtherEntities2")]
    partial class OtherEntities2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Sigcorp.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cpf");

                    b.Property<string>("NomeCompleto");

                    b.HasKey("ClienteID");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Sigcorp.Models.PedidoCompra", b =>
                {
                    b.Property<int>("PedidoCompraID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ClienteID");

                    b.Property<int>("NumeroPedido");

                    b.Property<double>("Total");

                    b.HasKey("PedidoCompraID");

                    b.HasIndex("ClienteID");

                    b.ToTable("PedidoCompra");
                });

            modelBuilder.Entity("Sigcorp.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.Property<int?>("PedidoCompraID");

                    b.Property<double>("ValorUnitario");

                    b.HasKey("ProdutoID");

                    b.HasIndex("PedidoCompraID");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("Sigcorp.Models.PedidoCompra", b =>
                {
                    b.HasOne("Sigcorp.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteID");
                });

            modelBuilder.Entity("Sigcorp.Models.Produto", b =>
                {
                    b.HasOne("Sigcorp.Models.PedidoCompra")
                        .WithMany("Produtos")
                        .HasForeignKey("PedidoCompraID");
                });
#pragma warning restore 612, 618
        }
    }
}
